### ISSUE TITLE
Connection with NodeJS Server

### ISSUE THREAD

**Issue by Matspyder51** [HunterNL/Gmod-Websockets#1]
It's possible, with your system, to connect a Gmod Server with a NodeJS Server using for exemple socket.io or something else ?
Because I need that for my server and I don't know how can I connect the two systems ?

**Comment by HunterNL** [comment]
Yes, you can connect to node.js with this. I'm using this myself to connect to a Meteor app which runs on node. Just run a websocket server on node and use this websocket client to connect with it.

**Comment by Matspyder51** [comment]
Ok, but can you make a small wiki to know what function correspond to what, and the parameters please, actually, I don't understand everything if I just look the .lua ?

**Comment by HunterNL** [comment]
I've added a bit of documentation in 68510f664e89f2429240af3e7d720f2d50d4773e
Let me know if you make something neat with this :)
