### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Be1zebub** [HunterNL/Gmod-Websockets#10]
I tried to use your library to develop a discord bot, I get a crash when trying to initialize the websocket client.
![image](https://user-images.githubusercontent.com/34854689/226160509-00095ef6-665d-4d98-8d94-b8d5ead56b73.png)

reproduce:
```lua
	local function initGW(url)
		print("init websocket", url)

		local client = websocket.Client(url)

		client:on("open", function(a, b, c)
			print(":on(\"open\")", a, b, c)
		end)

		client:on("message", function(a, b, c)
			print(":on(\"message\")", a, b, c)
		end)

		client:on("close", function(a, b, c)
			print(":on(\"close\")", a, b, c)
		end)

		client:on("ready", function(a, b, c)
			print(":on(\"ready\")", a, b, c)
		end)

		client:on("READY", function(a, b, c)
			print(":on(\"READY\")", a, b, c)
		end)

		client:Connect()
	end

initGW("wss://gateway.discord.gg")
```

**Comment by HunterNL** [comment]
Hey, thanks for your issue report!

I've had no luck reproducing the crash, could you say what platform you're running this on and what version of bromsock you are using?

I'd also note that the call to `websocket.Client()` requires a port number as second argument but that shouldn't by itself cause the crash.

**Comment by Be1zebub** [comment]
im on debian 11, kvm vps x86-x64 arch, i run my server in pterodactyl, i use https://github.com/Bromvlieg/gm_bromsock/blob/master/Builds/gmsv_bromsock_linux_ubuntu.dll bromsock build (because debian builds seems to be outdated & require libssl installed - idk how to install it properly)

**Comment by HunterNL** [comment]
I can't easily reproduce that environment at the moment but I do suspect the issue is with SSL. Does it still crash when connecting to a regular server (`ws://`) instead of a SSL enabled server (`wss://`)?

**Comment by Be1zebub** [comment]
uhh, okey - found a reason.
i got crash because of i call my `initGW` function in coroutine, I didnt even imagine that this could be the problem
to reproduce:
```lua
coroutine.wrap(function()
	initGW("wss://gateway.discord.gg")
end)()
```

its not ssl issue, i got crash with `ws://` protocol too

**Comment by Be1zebub** [comment]
its bromsock issue
https://github.com/Bromvlieg/gm_bromsock/issues/41
