### ISSUE TITLE
close event codes

### ISSUE THREAD

**Issue by hoksalot** [HunterNL/Gmod-Websockets#7]
sorry, not quite an "issue", could you please make onClose receive close event codes?

**Comment by HunterNL** [comment]
A lack of a feature can also be an issue ;)

This seems like a rather simple addition, but I don't have a development environment setup for this project right now. I might pick this up again at some point but I can't promise anything.

If you feel like giving it a go yourself a good place to start is [WS.Connection:onCloseMessage](https://github.com/HunterNL/Gmod-Websockets/blob/master/lua/autorun/server/websocket.lua#L864 ) and keep passing the exit code along until you reach the user callbacks.

**Comment by hoksalot** [comment]
thanks, i'll see what i can do tomorrow

**Comment by hoksalot** [comment]
could you give a few more clues? like what functions should i pass it through? because i don't really see this all through

**Comment by hoksalot** [comment]
i mean i always end up in a dead end

**Comment by hoksalot** [comment]
okay so i did a bit trash solution i'll make a commit and you'll see
